tosdr/edit.tosdr.org

app/views/shared/_navbar.html.erb
> Are you working on the latest release? 
yes
> Have you tested it locally?
yes
>  Please explain your change
In the mobile version of the website, the dropdown menu allowed link to pages that are only available for authenticated users. Nothing critical, it just lead to 500 errros.
=> [fix] fixing dropdown menu links in navbar

db/import_points_from_old_db.rb
With this change, `cd db; ruby import_points_from_old_db.rb` will successfully read in all the JSON files, but it can't save them into the RoR database because when it includes the Point model, it doesn't know where to look for Rails's ActiveRecord class. Maybe this should be run as a rake task?
=> feat: read JSON files

app/views/layouts/application.html.erb, app/views/shared/_alpha.html.erb
This is a infobox for the campaign. I expect few people to ask why they cannot add new services (as it already happened). Just making sure it won't happen again.
=> [enh] adding a flash about the alpha version

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_versions.scss, app/assets/stylesheets/pages/_point.scss, app/controllers/points_controller.rb, app/helpers/application_helper.rb, app/models/point.rb, app/views/layouts/application.html.erb, app/views/points/_table_reasons.html.erb, app/views/points/show.html.erb, db/migrate/20180414123052_add_change_reason_to_points.rb, db/schema.rb
* [enh] Please mention if it is a fix, enhancement or feature
Re-did the versions table on points to improve and add coherence. The versions are displayed now using bootstrap's collapsing panel functionality, which I find to be more user-friendly than the table that was there before. The panels rely on a newer version of bootstrap, which in turn has some jquery dependencies. I added those to the application.html.erb file. I created two helper methods: one to format the changeset datetimes, and another to handle empty changesets for the fields that we track, which currently includes "reason," "status," and "analysis," though more can be added and adapted. I also made some minor cosmetic changes to the point show page, basically just getting rid of those …
=> Versions formatting ux

app/controllers/points_controller.rb, app/views/points/_form.html.erb, db/migrate/20180424095751_remove_change_reason_from_points.rb, db/schema.rb
* [fix/enh] Please mention if it is a fix, enhancement or feature
We're tracking the 'reason' column on points in the changesets but didn't have a form input for it on the point update page. Added the form input. Also, there was another column on point called "change_reason" that wasn't being used that I removed via a migration.
Thanks !
=> added 'reason' form input to point edit page

app/controllers/points_controller.rb, app/controllers/reasons_controller.rb, app/views/points/_form.html.erb, db/migrate/20180424095751_remove_reason_from_points.rb
* EDIT: Reason model works in production, I can create a Reason through the console in production. Routes seem fine and :reason is permitted in the parameters in the PointsController. So my guess is that the error is in the Show.html.erb page. Somehow on edit content, :reason is not set and this could be why the app crashed. As in the form called in the edit method, there is reason
* DELETE: While we are at it, the delete button fails as well as it requests comments. One part of this PR drop the table comments all together (#YOLO).
Note: I created a "Test service" as a dummy to test into production, please use this one.
=> Fix show point in production

app/views/points/_table_reasons.html.erb
The points imported seem not to have a paper_trail version resulting in a unknown method. Only happening in production, let's see if this fixes it. 
Thanks !
=> quickfix for points that have nil versions

app/controllers/points_controller.rb, app/controllers/services_controller.rb, app/controllers/topics_controller.rb
Ok, this one might be a bit controversial as it won't allow not-logged users to see indexes of Topics, Points and Services. So just logged users can see them. I think that in the long term it could be cool to open that to not logged users but as Phoenix is a tool for work, this is why I made this choices because it could lead to errors through trying to access `/services`, `topics` or `points` through the url. 
I'm open for discussion for the next versions of the beta.
=> Force auth for some indexes

app/views/points/show.html.erb
I started working on this in December; the comments of a point are meant to be like [Wikipedia Talk pages](https://en.wikipedia.org/wiki/Talk:TL;DR), and I'm using it for importing the mailing list discussion thread import.
Continuing that now.
=> Bring back comments on points

app/models/service.rb, app/views/pages/home.html.erb, db/migrate/20180523100609_remove_grade_from_services.rb, db/schema.rb
More details about the exact changes can be found on the commit: f6d729102194e65aef47992332188c0b6cc43e20
Basically, what I've done is remove the storage of a service's grade in the database. When you accessed a service's grade through `Service.service_ratings`, not only was that grade recalculated, but the result was also (possible redundantly) inserted into the database. Thus, I've changed it to no longer store it in the database, under the assumption that code already never accessed `Service.grade` directly (since you could not be sure that it was up-to-date) - please do confirm if that assumption is true.
I also updated the view to use `Service.rating_for_view`, which appeared to have been written for that purpose - although I guess that logic should really belong in the view after …
=> [fix] Performance of the homepage

app/views/pages/home.html.erb
I've updated the sorting button label to reflect what the button is going to do when you click it, in a way that doesn't require you to think about what "ascending" or "descending" means :) I've limited it to just sorting by rating right now as that's probably (assumption) the main use case - although I guess sorting functionality is not that important for an MVP anyway.
I've also moved it to the right to make it less prominent, as I don't believe (assumption) it'd be used that often, and sorting options are usually located there.
Potential future improvements are to use icons rather than button states that usually represent primary and destructive actions (green and red colour, respectively), but since I don't think we've incorporated an icon set with the project yet, I've let that be …
=> [Enh] Improve sorting UX

app/assets/stylesheets/components/_card.scss
This is just a small change and I'm not sure to what extent we're catering to them and how attached we are to the shadows, but visually impaired users can have a hard time with the text-shadows that are currently in the application. Thus, I'd suggest removing them.
I've added @madoleary as a reviewer as she originally added them :)
=> [Enh] Remove text-shadows from cards

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_sort_button.scss, app/views/pages/home.html.erb
I've cleaned up the CSS a bit (using predefined variables instead of [magic numbers](https://css-tricks.com/magic-numbers-in-css/)).
Furthermore, I've moved the ratings to the right, so that the points are all equally aligned from the left-hand side, making them easier to scan.
Finally, I removed the hover effect from the cards, as that implied that you could interact with it, e.g. click it to get to the card page. Instead, you have to use the button at the bottom.
An, and this fixes #217.
=> [enh] Some UX tweaks for the homepage

app/controllers/points_controller.rb
The points view would _always_ load all points (in a greedy matter, too), even when you opted to just look at pending points.
Thanks !
=> Fix #430: "Pending points" view shows all points

app/views/points/_full_form.html.erb
The previous method of checking which text was selected
(.selectionStart and .selectionEnd) only worked on textareas,
which we removed. This now works again.
Also, the HTML of the scraped website was displayed - this commit
makes it so it's displayed as text.
The thing that doesn't work yet, and for which I think there's no
API available, it _setting_ the text selection to whatever was
previously selected.
Thanks !
=> [fix] Save selections back to the database

app/controllers/services_controller.rb, app/views/services/_form.html.erb, db/migrate/20180619101908_add_is_comprehensively_reviewed_to_services.rb, db/schema.rb
* [] Are you working on the latest release?
This is necessary for new ratings to actually show up on tosdr.org. Once a service has been marked as complete, the export script can include the ratings for services as calculated by Phoenix (see #459).
Note that services that currently have a rating available on tosdr.org are not yet marked as complete by the migration script, which might either be relevant for the export script, or require us to manually mark them as complete in the Phoenix interface.
Fixes #458.
=> [enh] Allow marking a service's review as complete

app/views/cases/_form.html.erb
The case weight was transformed to a drop-down to be able to set a
min and a max value, but this is also possible with the more
appropriate input[type="number"].
Furthermore, the weight is now set to 50 by default for new cases.
Thanks !
=> [enh] Use input[type="number"] for case weight

db/migrate/20180802102507_add_document_ref_to_points.rb
Fixes #569 - documents are now linked to points through a foreign key, rather than through a string. This improves performance and prevents data corruption.
Thanks !
=> [mod] Link documents to points through a foreign key

app/controllers/services_controller.rb, app/views/services/index.html.erb
In the service list, only show a link to the annotation view when
documents have already been defined for that service.
This has two advantages:
- Since adding documents currently requires knowledge of XPaths,
this makes it easy for contributors to see which services they
can immediately start annotating.
- For people who do understand XPath, it's easier to see which
services should still have XPaths added to them.
Longer-term, when annotation is the default mode, we can probably
show them all the time again. In fact, it'd probably be the
default target when you click the service name.
Fixes #623.
Thanks !
=> [enh] Only link to the annotation view with documents

app/helpers/application_helper.rb
Sanitize apparently removes tags it doesn't recognise (such as
<u>) and closes unclosed tags. This is undesirable for tags
crawled from a site's terms of service, since we want to preserve
its structure. It's also unnecessary, since those tags are not
parsed anyway, but displayed verbatim on-screen (in lieu of
successfully hiding them). Hence, we now first make sure that
they're displayed (by replacing `<` with `&lt;`, and likewise for
`>`), and only then sanitise our HTML.
Thanks !
Fixes #645, properly.
=> [fix] Sanitise content _after_ hiding included tags

app/views/points/show.html.erb
Fixes #685. Only point authors are now prompted to link that point
to a quote. (Since c601c6c9e785cc782f636d911df4dec5ee69473b, only
authors are allowed to do so.)
Thanks !
=> Only suggest point authors to link points to docs

app/helpers/application_helper.rb
Reverts tosdr/phoenix#690
Wow. For some reason this broke everything; apparently the comment breaks up the function chain or something. Sorry about that.
I'd move the comment, but that detaches it from the string it is about, so I guess future readers will have to do with the commit message...
=> Revert "Add a clarifying comment about showing entities"

app/helpers/application_helper.rb
I replaced special characters with their literal HTML entities, but
I did that after inserting my own special characters inside the
hidden tag. Switching over the order of the substitutions fixes it.
Fixes #684.
Thanks !
=> Fix selecting text containing hidden tags

app/controllers/pages_controller.rb
As opposed to points that were imported long ago, people who've
recently contributed to Phoenix probably care most, their points
are more likely to still be accurate, and their continued
participation would most benefit from their points quickly showing
up. Therefore make sure that pending points that have recently been
updated are listed first for curators.
Fixes #713.
=> List recently updated points first for curators

app/models/service.rb, app/views/shared/_table_services.html.erb
also added minor ux 'truncate' helper that truncates service names at 30 characters so that the table doesn't stretch across the page
Thanks !
=> added before_validation that strips attributes of trailing white space

app/views/services/_form.html.erb
Seems we were confusing the checkbox with some default values (issue #783 ), thus causing the bug on update for services that either have or have not been comprehensively reviewed. This fix should solve the problem.
Thanks !
=> fixing checked/unchecked update problem for 'comprehensively reviewed'

Gemfile, app/controllers/services_controller.rb, app/models/service.rb, app/models/user.rb, app/policies/service_policy.rb, app/views/services/_form.html.erb, app/views/services/index.html.erb, app/views/services/show.html.erb, config/initializers/recaptcha.rb, db/migrate/20190430102205_add_user_ref_to_services.rb, db/schema.rb
This ends our use of Google's recaptcha for service creation and updating, in favor of a different, independent solution. It's basically a hidden form field that scammers will detect and fill in, but real users will not. I also implemented a pundit policy for the service model, which involved a migration to connect users to the services that they create. Tested locally for non-logged-in users, logged-in users with no rights, and logged-in users with curatorial rights. Will do one more round of tests before merging.
Thanks !
=> 201904 captcha service

app/controllers/services_controller.rb, app/models/service.rb, app/views/services/_service_points.html.erb, app/views/services/show.html.erb, app/views/shared/_table_points.html.erb, config/routes.rb
This starts the re-design of the service show page that we talked about. I removed the filters for "pending" and "all" for service points, and I also removed the "order by rating" button. The points are now grouped by status, with "pending" points shown first, and ordered from best to worst within each status group.
Thanks !
=> 201905 service pending points

app/controllers/points_controller.rb
I am using the most recent version, and have tested this locally.
Closes #807 .
=> Reverse display of versions

app/controllers/points_controller.rb, app/controllers/services_controller.rb, app/views/api/v1/points/index.json.jbuilder, app/views/api/v1/points/show.json.jbuilder, db/migrate/20190629203821_remove_topic_from_points.rb, db/schema.rb
I am working on the latest release, I have tested this locally. Closes #846.
I am not *SURE* about all the removals of references to topic_id -- so please check those over carefully.
=> Remove topic_id from points

app/helpers/application_helper.rb, app/views/pages/home.html.erb, app/views/points/_table_versions.html.erb, app/views/services/_versions.html.erb
I am working on the latest release, and have tested locally. Closes #849.
The version history display should use the `created_at` field on the version, not the description of the changes of the `updated_at` field on the underlying object.
=> Remove format_time as confusing

app/controllers/cases_controller.rb, app/views/cases/show.html.erb, app/views/shared/_table_cases.html.erb
This adds an optional query parameter `status` to the Case overview that allows you to filter its points by status (e.g. `?status=pending`).
It also makes the count of pending Points in a table of Cases (such as on a Topic page) link to a list of Points in that Case filtered by `pending` status.
Fixes #862.
=> Make pending count a link

app/views/pages/about.html.erb, app/views/services/index.html.erb
The button on the services page to add a new service disappears one the table has finished loading
This PR removes the cloak option as its not needed anyway to display the button when the table has finished loading.
This fixes #931
=> Removed add service button cloak on service page. Fixes #931

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/user_mailer/welcome.html.erb
* [ x] Have you tested it locally?
links were created using `herf` and not `href`, thus breaking them in emails
Thanks !
=> fixing broken links in emails
