- app/controllers/points_controller.rb
Removing user_id from the params needed to set up points
> updating points controller methods

- public/404.html
- public/500.html
> Revert "fix conctact us link"

- README.md
Fixed a broken link to the project's wiki in the README file.
> Fix wiki link in README

- db/import_services_from_old_db.rb
- db/import_topics_from_old_db.rb
Trying to make indentation consistent between the three import scripts.
> [enh] indentation

- db/import_points_from_old_db.rb
> fix: import from old db (continued)

- app/views/pages/home.html.erb
> [enh] Putting the original tagline in Phoenix

- app/views/pages/home.html.erb
- app/views/points/_table.html.erb
- app/views/services/show.html.erb
* Are you working on the latest release?
hope so 
* Have you tested it locally?
yes 
* If troubles, have you checked your ruby and rails version? 
* If changes in the database, have you ran `rails db:migrate`?
* Please mention if it is a fix or enhancement
enhancement ! 
* Please explain your change
so I added a button that reorders depending on its own class
Thanks !
>  [enh] ordering services and poinst on ratings

- app/controllers/services_controller.rb
- db/import_points_from_old_db.rb
- db/import_posts_from_old_db.rb
- old_db/points/0OpLZGJCMPY.json
- old_db/points/OqIkAS2uwmE-7.json
> [WiP] Point status

- app/models/user.rb
- app/views/pages/about.html.erb
- config/environments/production.rb
- config/initializers/active_admin.rb
- config/locales/devise.en.yml
- db/migrate/20171220095528_add_deactivate_to_users.rb
- db/schema.rb
> [fix] fixing deletion of user's account even if there are contributions

- app/controllers/topics_controller.rb
- app/views/services/_form.html.erb
- app/views/topics/_form.html.erb
- app/views/topics/index.html.erb
- app/views/topics/show.html.erb
- db/migrate/20171223150303_adding_privacy_related_to_services.rb
- db/migrate/20171223151948_adding_privacy_related_to_topics.rb
- db/schema.rb
Adding a boolean field "privacy_related" to services. No view implementation yet. 
Thanks !
> [enh] adding privacy related boolean column to topics

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/assets/stylesheets/components/_sort_button.scss
- app/views/pages/home.html.erb
- app/views/points/_table.html.erb
- app/views/services/show.html.erb
Improving the view of the buttons implemented by  @gkosmo. If we plan to make more of them, this layout allows it
Thanks !
previous had a bad base
> WIP: [enh] refacto pull #195

- app/views/shared/_navbar.html.erb
> FIX: fixing the routing for the sign up page

- app/assets/stylesheets/components/_index.scss
- app/views/services/show.html.erb
- db/schema.rb
Show the class on the show service page
> Adding the class on the show service page and styling

- config/environments/production.rb
>* [X] Have you tested it locally? 
Production test is necessary
>* [X] Please explain your change
Changed the base email
> [fix] changing the base url in the production environment

- app/views/points/_form.html.erb
Implementing "cases", categories of types of points (such as "cannot delete account") so they can have the same type of rating cross-services. Most of them are [here](https://github.com/tosdr/tosdr.org/tree/master/cases). Please comment if there is any issues.
Thanks !
> [WIP] Implementing cases

- db/migrate/20171214143221_create_comments.rb
> build passed, committing for real

- Gemfile.lock
- app/controllers/points_controller.rb
- app/controllers/reasons_controller.rb
- app/controllers/services_controller.rb
- app/controllers/topics_controller.rb
Fixing a URL fuzzing vulnerability: non logged users could access /topics/new and add a new topic. Although, a 500 was return the topic was created. This vuln worked for points and services. 
It was fixed by adding the necessity to authenticate users in the controller. 
Also, I fixed the gemfile (vuln in loofah)
> [Sec] Url fuzzing vuln

- app/controllers/pages_controller.rb
- app/models/service.rb
* [ x] Are you working on the latest release?
* [ x] Have you tested it locally?
* [ fix/enh] Please mention if it is a fix, enhancement or feature
* [ -->] Please explain your change
I added a scope on services in service.rb that filters the services by whether they have points. I added the scope to @services in the pages_controller.rb file so that only services with points are sent to the view.
Thanks !
> scope on services so only services with points show up on home page

- config/routes.rb
* [ x] Are you working on the latest release?
* [x ] Have you tested it locally?
* [fix ] Please mention if it is a fix, enhancement or feature
Fixed the issue with points/new.
Thanks !
> fixed points/new

- app/assets/stylesheets/pages/_service.scss
- app/views/services/show.html.erb
Changing some font weight and colors to make the display more clear.
> [enh] changing colors and font weight for better lisibility on service show page

- app/views/services/show.html.erb
Well that was fun! Fixed the 500 error in production which was due to current_user evaluating to nil for people who aren't logged in. :)
Thanks !
> fixed current_user 500 error in prod

- app/views/points/_table.html.erb
- app/views/points/show.html.erb
- app/views/services/_table.html.erb
- app/views/services/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/topics/index.html.erb
- app/views/topics/show.html.erb
- config/initializers/devise.rb
> [fix & mod] Prod fixes

- app/controllers/points_controller.rb
- config/routes.rb
Fixed the routing issues with featured points by defining outside of the member.
Thanks !
> fixed routing for featured points

- app/models/user.rb
- config/initializers/devise.rb
> [WIP] [enh] Stronger password policy

- config/routes.rb
there was a bug in the is_featured route that i fixed by changing the route from "get" to "put."
Thanks !
> corrected put method in routes to fix is_featured bug

- app/controllers/points_controller.rb
- app/controllers/reasons_controller.rb
- app/views/points/_form.html.erb
- db/migrate/20180424095751_remove_reason_from_points.rb
> Revert "Fix show point in production"

- db/migrate/20180502084249_remove_change_reason_to_points.rb
- db/migrate/20180502084404_add_change_reason_to_points_again.rb
- db/schema.rb
> dirty fix for the missing method in production

- app/views/points/_table_reasons.html.erb
> Revert "quickfix for points that have nil versions"

- app/views/points/show.html.erb
Wrote an overarching exception for points with no versions.
Thanks !
> exception for handling points with no versions

- app/views/points/_table_reasons.html.erb
> Revert "Reverting previous changes"

- app/controllers/points_controller.rb
Curator in the points controller was not allowing users to create points. 
Thanks !
> fix for issue 320, unauthorized access was too strong

- app/models/point.rb
Fixing #262 
I added a `has_many :comments, dependent: :destroy` in `point.rb`
> Fixing issue 262

- app/controllers/points_controller.rb
* [enh] Please mention if it is a fix, enhancement or feature
Thanks !
> [enh] adding notice after deletion of point

- app/views/pages/home.html.erb
- public/nothing.html
Fix: #290 (only for home page as it was the only one missing
Thanks !
> Fix: adding a new nothing error message file 

- app/views/points/show.html.erb
> Fix: adding a link for the source of the point

- README.md
- db/export_points_to_old_db.rb
- db/export_services_to_old_db.rb
implementing services export from phoenix to the website.
should probably use phoenix id's for services as well (just like for points).
should discuss whether we want to display the classes that phoenix has assigned to a lot of services, or think about the rules for that a bit more.
> [WiP, do not merge] export services

- Gemfile
- Gemfile.lock
- app/controllers/pages_controller.rb
- app/controllers/points_controller.rb
- app/controllers/services_controller.rb
- config/environments/development.rb
- config/environments/test.rb
Used the [Bullet](https://github.com/flyerhzm/bullet) to optimize the n+1 call to the database and hopefully speeding the app.
> Performance: applying changes required by Bullet library

- app/mailers/user_mailer.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/mailer.html.erb
- app/views/user_mailer/status_update.html.erb
- app/views/user_mailer/welcome.html.erb
<strike>* [ ] Have you documented your feature on the wiki? </strike>
Adding styling and more details to the mailers
> [enh] Rebranded the welcome message

- PULL_REQUEST_TEMPLATE.md
- db/export_points_to_old_db.rb
- db/export_services_to_old_db.rb
Safe to merge because none of these changes affect the RoR site.
> Push latest master to production

- app/models/user.rb
> [fix] adding a patch to manage reasons

- app/models/user.rb
> fix for reason reassignement

- db/export_services_to_old_db.rb
> dont build none service

- app/controllers/points_controller.rb
* [fix] Please mention if it is a fix (fix), enhancement (enh), modification (mod) or security (sec)
Fixed issue #355 by adding exception for errors on update in points controller.
Thanks !
> fixed silent errors on point update

- app/views/points/_form.html.erb
The previous instructions were made inaccurate by
f38fbbdcf1f6e10da32d7ba09226ef8098ebf73c.
> [fix] Update instructions for updated form

- db/import_posts_from_old_db.rb
> [WiP] feat: import mailing list posts

- app/views/points/show.html.erb
> Remove 'Delete Point' option

- app/views/pages/home.html.erb
> [fix] Add label data for sorting to services

- app/assets/stylesheets/components/_card.scss
> [fix] Add vertical whitespace between cards

- app/assets/stylesheets/components/_card.scss
> [fix] Truncate names of services with spaces

- app/views/cases/index.html.erb
- app/views/cases/show.html.erb
> [fix] Do not error when not logged in on the cases page

- app/controllers/cases_controller.rb
- app/models/case.rb
- app/views/cases/index.html.erb
Fixes #390.
It would be nice if someone with more experience with Ruby and RoR could take a quick look to see whether this is the right approach :)
> [enh] Support searching for cases

- app/models/point.rb
> [enh] Also allow searching for points by title

- app/controllers/points_controller.rb
- app/views/services/_table.html.erb
- config/routes.rb
> [enh] Link to point creation on the service page

- app/controllers/points_controller.rb
- app/controllers/services_controller.rb
- app/views/services/_table.html.erb
- app/views/services/show.html.erb
- config/routes.rb
> [fix] Allow setting the Wikipedia link for a service, and only show the Wikipedia logo when that link is set

- app/views/shared/_navbar.html.erb
* <strike>[ ] If necessary, have you documented your feature on the wiki? </strike>
I fixed the alignment on the navbar, it wasn't properly aligned.
> [fix] Fixing alignment between 'About' and 'Login + Sign up'

- app/controllers/points_controller.rb
- app/views/points/_full_form.html.erb
- db/migrate/20180530131412_add_tosback_to_point.rb
- db/schema.rb
Still a draft, it's not finished yet, but retrieving the Tosback2 crawled doc from github works, and so does selecting a quote from within the textarea! :)
> add tosback quoting

- Gemfile
- Gemfile.lock
This was useful to fix issue 258, so might as well keep it in
during development:
https://github.com/tosdr/phoenix/issues/258#issuecomment-391298098
It adds console messages point to where queries originated.
Thanks !
> [mod] Add a Gem to debug SQL queries

- config/initializers/active_record_query_trace.rb
This was supposed to go in
fbdf5d6edc2ed3d3878310008b6bcfde2f59131c, but I forgot >.<
Thanks !
> [fix] Add ARQT initialiser

- app/assets/stylesheets/components/_form.scss
- app/views/points/_full_form.html.erb
> [enh] making the appearing quote into a scrollable div + styling

- config/environments/development.rb
- config/initializers/active_record_query_trace.rb
> [fix] Only load ARQT in development

- app/views/services/annotate.html.erb
- db/export_points_to_old_db.rb
This fix was instructed by Michiel.
> [fix] Remove failing return statement

- app/views/services/annotate.html.erb
> Fix #472: Fetch terms for ToSBack-reviewed sites

- app/views/services/annotate.html.erb
See the commit messages for details on the fixes.
> Fix annotation selection

- app/views/points/_full_form.html.erb
> Workaround: Also limit ourselves to reviewed crawls for edits

- app/views/services/annotate.html.erb
> [enh] Link point IDs in the annotate view to points

- app/views/shared/_alpha.html.erb
> [enh] Update Alpha message to state that it can be used

- app/controllers/pages_controller.rb
- app/models/service.rb
- app/views/pages/home.html.erb
> [enh] Home page layout

- app/views/points/show.html.erb
> [enh] Link to a point's service from the point page

- app/views/points/_table.html.erb
> Fix #519: Add links to services and points

- app/views/services/annotate.html.erb
Rather than having to select some text, then scrolling all the way up, clicking the button next to a quote, and then clicking save, you can now select some text, after which a dropdown with all points will pop-up, from which you can select and then immediately annotate.
> [enh] Improve annotation workflow

- app/views/cases/show.html.erb
- app/views/pages/home.html.erb
- app/views/points/_table.html.erb
- app/views/services/_table.html.erb
- app/views/topics/show.html.erb
This should 500 Internal Server errors currently experienced on `/points` (and certain other views).
> [fix] Only show ratings when they are available

- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
- app/views/services/index.html.erb
- app/views/services/show.html.erb
- db/export_services_to_old_db.rb
> [fix] Use Service.service_rating as the ratings source

- .gitignore
- app/views/points/show.html.erb
- db/export_points_to_old_db.rb
> export fixes

- app/views/points/show.html.erb
> link to case

- app/assets/stylesheets/components/_card.scss
- app/models/service.rb
- app/views/pages/home.html.erb
> [fix] Services without approved points should be N/A

- app/views/cases/_form.html.erb
- db/export_points_to_old_db.rb
> fix case.classification getting set to a number

- app/models/service.rb
Now in the model the line ` self.points.where(status:"approved").size == 0` will check if the point has approved point before assigning it a rating. Works for me in local. I'd like to have someone else's opinion on that before merging. 
It shouldn't break in the case where a Service has only draft or declined point either, so I guess this is good.
> [fix] Fix #554

- app/views/layouts/application.html.erb
- app/views/shared/_alpha.html.erb
- app/views/shared/_beta.html.erb
<strike>* [ ] If necessary, have you documented your feature on the wiki? </strike>
See #561
> [fix] renaming the alpha in beta in the flash on the website (561)

- app/views/cases/index.html.erb
- app/views/services/show.html.erb
<strike>* [ ] If necessary, have you documented your feature on the wiki? </strike>
See #574 (is it what you were talking about right @michielbdejong ?)
> Fix: removing the archived version scope (574)

- app/views/cases/_form.html.erb
<strike>* [ ] If necessary, have you documented your feature on the wiki? </strike>
Fixing #457 by fixing the range with a selection from 0 to 100, also adding 50 as a preselected value.
> Fix: range with a selection from 0 to 100 for Cases (457)

- app/assets/stylesheets/components/_card.scss
- app/controllers/cases_controller.rb
- app/models/point.rb
- app/views/cases/index.html.erb
- app/views/cases/show.html.erb
> Fix: Case views, showing rating of a case (rough), searchbar on Case index, eager calls (566++) 

- app/controllers/points_controller.rb
- app/views/points/_full_form.html.erb
Improves #425, although it's still too hard to select a case for a point, in my opinion. That said, this PR makes it somewhat easier by grouping the cases by topic.
Thanks !
> [enh] Group cases by topic in the points form

- app/views/points/_full_form.html.erb
> [enh] Set new points as "Pending" by default

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_versions.scss
- app/views/pages/home.html.erb
The versions panels are not actually interactive, so the hover
effect was misleading.
Fixes #559.
Thanks !
> [enh] Remove hover styles from panel

- app/views/documents/show.html.erb
> [enh] Link back to annotate view from the document view

- app/controllers/services_controller.rb
- app/models/document.rb
- app/views/services/annotate.html.erb
> [enh] Select cases when annotating, creating new points instead of linking existing points to documents

- Dockerfile
- app/assets/stylesheets/pages/_annotate.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/documents_controller.rb
- app/views/documents/_form.html.erb
- app/views/services/annotate.html.erb
> [enh] 590 add document from annotate

- app/controllers/documents_controller.rb
> [enh] Find the new locations of quotes after recrawling

- app/views/services/annotate.html.erb
> [fix] Only allow annotation of single documents

- app/models/document.rb
> [fix] Allow multiple documents at the same URL

- app/controllers/documents_controller.rb
> [fix] Redirect to a relative path, rather than to localhost, when saving a document

- app/assets/stylesheets/pages/_annotate.scss
- app/controllers/services_controller.rb
- app/views/services/annotate.html.erb
> [enh] Improve layout of the annotate view using Bootstrap components

- app/views/points/show.html.erb
> [fix] Also hide tags on the points view

- app/assets/stylesheets/pages/_annotate.scss
- app/controllers/services_controller.rb
- app/views/points/show.html.erb
- app/views/services/annotate.html.erb
- config/routes.rb
> [enh] Allow setting and changing a point's annotation

- app/views/services/_form.html.erb
> [enh] Don't show "complete" checkbox for new services

- app/assets/stylesheets/pages/_annotate.scss
> [fix] Hide tags again, such that it also works in Chrome

- app/assets/stylesheets/pages/_annotate.scss
> [enh] Add a max-width for the case selection dropdown

- app/views/services/annotate.html.erb
Fixes #655, and hopefully also improves upon #618.
Thanks !
> [fix] Fix 32-bit characters tripping up quote selection

- app/controllers/points_controller.rb
> [mod] Allow optional analysis

- app/controllers/points_controller.rb
- app/models/point.rb
This reverts fb5ef75dec95cc9a80c9a5dc02262604a87066bd, which
attempted to do the same but was the incorrect way of going about
that - sorry.
Fixes #667.
Thanks !
> [fix] Store a point's analysis, and make optional

- app/controllers/pages_controller.rb
- app/controllers/points_controller.rb
- app/mailers/user_mailer.rb
- app/models/point.rb
- app/views/pages/home.html.erb
- app/views/points/_full_form.html.erb
- app/views/points/new.html.erb
- app/views/points/review.html.erb
- app/views/services/index.html.erb
- app/views/services/show.html.erb
- app/views/shared/_navbar.html.erb
- app/views/user_mailer/reviewed.html.erb
- app/views/user_mailer/reviewed.text.erb
Will show to @Vinnl before merging
> Deprecate point adding and hide beginner instructions from curators

- app/models/document.rb
> change debug statement to fix #663

- app/controllers/services_controller.rb
- app/views/points/show.html.erb
> [mod] 674 annotation permissions

- PULL_REQUEST_TEMPLATE.md
- app/views/services/_table.html.erb
- app/views/services/annotate.html.erb
- app/views/services/show.html.erb
> Make annotation the primary review method

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
Show a user's own points that are in draft mode or have changes
requested on them by a curator on the homepage.
Fixes #676.
Thanks !
> Highlight changes-requested and draft points

- app/helpers/application_helper.rb
> Add a clarifying comment about showing entities

- app/controllers/topics_controller.rb
- app/views/topics/index.html.erb
- app/views/topics/show.html.erb
> List cases under a topic, rather than points

- app/controllers/points_controller.rb
- app/views/points/_full_form.html.erb
> Enable declining one's own points

- app/models/document.rb
> Don't show declined points in the annotation view

- app/controllers/services_controller.rb
- app/views/services/_form.html.erb
> Only allow curators to mark a review comprehensive

- db/export_services_to_old_db.rb
> strip whitespace from domains, fix #687

- app/controllers/services_controller.rb
> Redirect to newly created service

- app/views/points/review.html.erb
> Don't prefill previous comments when reviewing

- app/controllers/pages_controller.rb
- app/controllers/points_controller.rb
- app/controllers/services_controller.rb
- app/models/service.rb
- app/views/cases/show.html.erb
- app/views/pages/home.html.erb
- app/views/points/_table.html.erb
- db/migrate/20181001095312_remove_featured_from_points.rb
- db/schema.rb
* [ x] Are you working on the latest release?
* [ x] Have you tested it locally?
I created a migration to remove the is_featured property on points and removed all references to is_featured from the application views and controllers.
Thanks !
> 201810 remove feature

- app/views/points/_table.html.erb
I got rid of the complex card-based component that was widely used to display points in the application, in favor of a bootstrap table. It makes a big improvement, UX-wise. If this is agreeable, I can implement the table in place of all the other instances of the card-based component in the app (for example, what we use to display services, cases, and topics).
Thanks !
> implementation of bootstrap table for points

- app/controllers/topics_controller.rb
- app/views/topics/_form.html.erb
- app/views/topics/index.html.erb
- app/views/topics/show.html.erb
- db/migrate/20181101123536_remove_privacy_related_from_topics.rb
- db/schema.rb
Removing privacy_related from topics, as well as references to it in the application, as discussed in issue #740 .
Thanks !
> 201811 remove privacy related from topics

- app/controllers/services_controller.rb
- db/schema.rb
> Only curators can update services

- config/initializers/rack_attack.rb
I'm adding a more helpful error message for users in the event that they run afoul of our current rate-limiting protections.
Thanks !
> customized message for users

- app/assets/stylesheets/application.scss
- app/controllers/documents_controller.rb
- app/models/document.rb
- app/views/documents/_form.html.erb
- app/views/documents/_table_documents.html.erb
- app/views/documents/index.html.erb
- app/views/documents/show.html.erb
- app/views/shared/_navbar.html.erb
- config/environments/development.rb
- config/environments/production.rb
- improved ux of documents index, document show page
- made more robust search functionality on documents index
- added custom validation for uniqueness of url and xpath that provides an error message with a link to the existing document when the uniqueness validation fails
- made it so that "crawl" is called only after a document passes its validations
- added 'documents' to navbar so the index page is easily accessible to users
Thanks !
> 201902 improving document errors

- app/controllers/services_controller.rb
- app/models/point.rb
- app/models/topic.rb
- app/views/services/annotate.html.erb
This will order the topics by frequency of use on the annotate drop down, which will hopefully make case-selection easier.
Thanks !
> 201903 cases list annotate

- app/controllers/documents_controller.rb
- app/controllers/services_controller.rb
- app/models/document.rb
- app/models/user.rb
- app/policies/document_policy.rb
- app/views/documents/show.html.erb
- config/routes.rb
- db/migrate/20190414103207_add_user_ref_to_documents.rb
- db/schema.rb
- lib/tosbackdoc.rb
Lots going on in this PR. 
First and foremost, I implemented rights management for documents with Pundit. We need to expand Pundit's rights management to the rest of the models and their controllers, but hopefully this can be a good test round. This type of broader rights management will really bolster our security. I also did a migration to index users on documents, so that a document can now be linked to the user who created it.
- users who have created a document can edit and update it; curators can edit and update any document, as was the case before.
- users who are not curators can only "crawl" documents that they've created; before, anyone could "crawl" any document; I found this risky, seeing as if a document's xpath is no longer valid, the …
> 201904 document rights

- app/controllers/users/registrations_controller.rb
- app/views/users/registrations/new.html.erb
We confirm users via email, so removing the captcha requirement on sign-up.
Thanks !
> removing captcha for user sign-up

- app/views/layouts/application.html.erb
- app/views/shared/_beta.html.erb
> Removing beta

- app/models/user.rb
Narrowing password validation on user so that it doesn't trip-up other updates to user attributes, such as updates to email or username.
Thanks !
> narrower validation for password

- app/controllers/documents_controller.rb
- app/controllers/users/sessions_controller.rb
> removing unnecessary flash messages

- config/environments/production.rb
> attempt to fix js compilation error in production

- app/views/shared/_table_points.html.erb
- docker-compose.yml
> List quote instead of point title if available

- app/assets/javascripts/application.js
- app/assets/javascripts/services/annotate.js
- app/views/services/_service_points.html.erb
- app/views/services/_table.html.erb
- app/views/services/index.html.erb
- app/views/shared/_table_points.html.erb
The functions for sorting services and points had the same name,
even though they behaved differently (i.e. sorting on A, B, C, etc.
vs. on Good, Bad, etc.), and therefore did not work.
I also changed IDs to class names, since they weren't unique.
Fixes #817.
>  Fix conflicting function names 

- app/assets/javascripts/services/table.js
- app/views/services/_table.html.erb
This ought to fix outstanding issues with the sorting mechanism on the services index page, referenced in issue #822 . 
Thanks !
> fixing sort, dedicated javascript file for the function

- app/views/points/index.html.erb
- app/views/shared/_table_points.html.erb
> fixing headers issue in points table, adding responsive class to table

- app/controllers/points_controller.rb
- app/policies/point_policy.rb
- app/views/points/_full_form.html.erb
- app/views/points/edit.html.erb
- app/views/points/index.html.erb
- app/views/points/new.html.erb
- config/routes.rb
First big push in an effort to reduce technical debt in the application by refactoring one of the primary controllers and its associated views. Also created and implemented a formal policy to strengthen security.
Thanks !
> 201906 refactor

- app/views/cases/_form.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/pages/about.html.erb
- app/views/pages/home.html.erb
There are a number of infelicitous or awkward wordings in the site; this is an attempt to improve various of them.
> A big pile of wording changes (hopefully improvements!)

- app/views/shared/_table_cases.html.erb
It'd be nice to see how many points each case has pending, so the ones with lots can be focused on first.
> Add count of pending points per case

- app/controllers/points_controller.rb
- app/policies/point_policy.rb
- app/views/points/show.html.erb
- config/routes.rb
See #831 . This also switches the drop-down menu to buttons, as I requested in #832 .
> Add one click approval

- app/views/services/_table.html.erb
Make the last column of the Services table either a link to annotate existing documents, or upload a new one if there aren't any.
> Improve usefulness of Services table

- INSTALL_linux.sh
- db/seeds.rb
I am working on the latest release, and have tested my changes locally. The script to install rbenv didn't actually work correctly. I'm still not sure if the PATH is being set properly...
> Fix install linux

- app/assets/javascripts/services/table.js
- app/controllers/points_controller.rb
- app/controllers/services_controller.rb
- app/views/services/_table.html.erb
- app/views/shared/_table_cases.html.erb
Various suggestions from previous PRs and other minor cleanup.
> Add pending counts to services

- README.md
I think @JesseWeinstein belongs to this list, no? :)
> Add Jesse to list of core contributors

- app/models/service.rb
- app/views/services/_table.html.erb
> putting pending points count in an instance method

- Gemfile
- Gemfile.lock
> updating puma

- app/controllers/services_controller.rb
> fixing eager loading on service index

- Gemfile
- Gemfile.lock
- app/controllers/services_controller.rb
- app/models/service.rb
- app/views/services/_table.html.erb
- config/schedule.rb
- lib/tasks/service.rake
> adding cron task and adjusting rating method to pull from generated csv

- app/models/service.rb
> fixing method name error

- app/views/pages/home.html.erb
- app/views/services/show.html.erb
- db/export_services_to_old_db.rb
> fixing references to service_rating

- app/controllers/case_comments_controller.rb
- app/controllers/document_comments_controller.rb
- app/controllers/point_comments_controller.rb
- app/controllers/service_comments_controller.rb
- app/controllers/topic_comments_controller.rb
- app/views/case_comments/_form.html.erb
- app/views/document_comments/_form.html.erb
- app/views/point_comments/_form.html.erb
- app/views/service_comments/_form.html.erb
- app/views/topic_comments/_form.html.erb
adding honeypots to comment creation across models to prevent bot spam
Thanks !
> implementing honeypot for comments

- app/controllers/spam_controller.rb
- app/controllers/topic_comments_controller.rb
- app/models/case_comment.rb
- app/models/document_comment.rb
- app/models/point_comment.rb
- app/models/service_comment.rb
- app/models/spam.rb
- app/models/topic_comment.rb
- app/policies/spam_policy.rb
- app/views/cases/show.html.erb
- app/views/documents/show.html.erb
- app/views/points/show.html.erb
- app/views/services/show.html.erb
- app/views/shared/_comments.html.erb
- app/views/topics/show.html.erb
- config/routes.rb
- config/schedule.rb
- db/migrate/20200516123903_create_spams.rb
- db/migrate/20200517080230_add_user_and_cleaned_to_spams.rb
- db/schema.rb
- lib/tasks/spam.rake
added mechanism for marking comments as spam, to be deleted automatically by a rake task, with records of their deletion stored in "spam" polymorphic table. 
Thanks !
> Comments -- spam prevention

- app/assets/javascripts/services/index.es6
- app/views/services/index.html.erb
* [x ] Are you working on the latest release?
* [x ] Have you tested it locally?
* [ x] Please explain your change
the 'add service' button wasn't appearing on the services index page for curators. i added it back.
Thanks !
> fixing add service button

- app/views/pages/about.html.erb
Just fixing a typo and change wording from encryption (reversible) -> hashing (not reversible)
> fix typo/wording on Password storage

- app/controllers/cases_controller.rb
- app/views/cases/index.html.erb
- app/views/topics/show.html.erb
This PR adds descriptions as tooltips to the case overview
Fixes #903
> Added descriptions of cases as tooltips to the case overview.

- app/controllers/api/v1/points_controller.rb
- app/views/api/v1/points/index.json.jbuilder
addresses ongoing concerns with #938 
Thanks !
> fixing points-side api

- app/assets/javascripts/services/index.es6
> allowing services search by domain

- app/controllers/api/v1/services_controller.rb
- app/views/api/v1/services/index.json.jbuilder
paginates API's json response for services
Thanks !
> applying pagination to services

- app/views/api/v1/cases/index.json.jbuilder
- app/views/api/v1/cases/show.json.jbuilder
addresses need for case weight in api #941 
Thanks !
> making case weight available via api

- app/controllers/topics_controller.rb
- app/views/topics/index.html.erb
> making topics index page available to unauthenticated users

- app/controllers/documents_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/services_controller.rb
- app/policies/document_policy.rb
- app/views/documents/_form.html.erb
- app/views/documents/show.html.erb
- app/views/points/show.html.erb
- config/routes.rb
> Bring back crawl button

- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/pages/home.html.erb
- app/views/points/_table_versions.html.erb
- app/views/points/show.html.erb
- app/views/services/_service_points.html.erb
- app/views/services/_versions.html.erb
- app/views/shared/_comments.html.erb
- app/views/shared/_table_points.html.erb
This PR adds Labels to mark curators and team members on various sections of the site
> Adding Team and Curator Labels

- app/helpers/application_helper.rb
catching nil user edge case on service show to avoid 500 error #964 
Thanks !
> Fix nil user

- app/helpers/application_helper.rb
> trying build again

- lib/tasks/service.rake
https://tosdr.atlassian.net/browse/ROAD-31
> ROAD-31 transliterate slugs now and revert back to ID if transliteration failed

- Gemfile
- config/initializers/sentry.rb
- public/500.html
* [ x Have you tested it locally?
Thanks !
https://tosdr.atlassian.net/browse/EDIT-89
> EDIT-89 Add Sentry

- app/models/document.rb
* [ x] Are you working on the latest release?
* [ x] Have you tested it locally?
this is hot fix for the server error thrown by nil classes on certain document show pages
Thanks !
> fixing server error on certain document show pages in production

- app/models/document.rb
i'm removing the puts logs in the else condition that are breaking document load in production. this also removes the else condition.
Thanks !
> Document nil class failure

- README.md
Changed CONTRIBUTING.md to QUICKSTART.md to match the rename from an earlier commit. Also added a link to the file.
Thanks !
Change: I updated the README changing CONTRIBUTING.md to QUICKSTART.md since the file was renamed. I also added a link to QUICKSTART.md
(Since this was only a small fix to a README, I didn't create a Jira issue or have an issue key. Let me know if I should do this.)
Fixes #1093 #1093
> Updated README to reflect file rename

- app/controllers/documents_controller.rb
Fixes error when trying to convert nil to string on document_comment creation.
Thanks !
> fixing nil to string error, refactor

- README.md
Thanks !
Just added the gitpod badge
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/tosdr/edit.tosdr.org)
> Add Gitpod to Readme

- app/controllers/pages_controller.rb
- app/controllers/services_controller.rb
- app/helpers/application_helper.rb
- app/models/case_comment.rb
- app/models/document_comment.rb
- app/models/point_comment.rb
- app/models/service_comment.rb
- app/models/topic_comment.rb
- app/models/user.rb
- app/models/version.rb
- app/views/cases/show.html.erb
- app/views/documents/show.html.erb
- app/views/pages/home.html.erb
- app/views/points/_table_versions.html.erb
- app/views/points/list_docbot.html.erb
- app/views/points/show.html.erb
- app/views/services/_service_points.html.erb
- app/views/services/_versions.html.erb
- app/views/services/show.html.erb
- app/views/shared/_comments.html.erb
- app/views/shared/_table_points.html.erb
- app/views/topics/show.html.erb
Thanks !
Broadly, this PR would remove redundant look-ups of user objects, unless absolutely necessary.
> Fixes heavy queries to resolve n+1 issues in production

- app/models/document.rb
- db/migrate/20231211184004_add_ota_sourced_to_documents.rb
- db/schema.rb
- lib/tasks/documents.rake
* [see title] Please explain your change
Thanks !
> fetches document text from ota github

- Dockerfile
- config/environments/production.rb
- config/environments/staging.rb
> bump Debian to fix pipeline 
